apiVersion: v1
kind: Pod
spec:
  containers:
  - name: build
    image: alpine:latest
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - infinity
